Add PTB and Canary versions
palfrey/discord-apt pull request #10
Opened 2024-08-05 08:53 UTC by Gabriel29306

# Description
This PR permit to satisfy the #8 issue.
This PR reformat the code to be reusable between different versions of discord.

# Modifications
- Rename the `packages.json` file in `stable_packages.json`.
- Add `ptb_packages.json` and `canary_packages.json` for the differents versions.
- Transform the main code to a function to be reused.
- Use the function for all versions.

> [!Note]
> If needed, I can modify the code as you need.

2024-08-06 20:16 UTC, palfrey requested changes
Looks pretty good. There's a couple of comments below, and also the README will need updating to note the 3 different packages, but happy to merge if those can get resolved.

2024-08-06 20:16 UTC, palfrey commented on get_new_package.py
> +        return 1
The return 0/1 was an exit code. For this version, it should return a bool from this function and if any of the calls to this return true, return 0 else 1

2024-08-06 20:16 UTC, palfrey commented on get_new_package.py
> +stable_filename = stable_url.split("/")[-1]
Other than the varying URL, I'm seeing the same code here for stable/ptb/canary which could just be folded into one big "download stuff" function

2024-08-06 20:53 UTC, Gabriel29306 commented
Is it good for you or you need a other change ?

2024-08-06 22:30 UTC, palfrey commented
> Is it good for you or you need a other change ?

Can you please fix the conflict with `packages.json` - I think the stable list just updated since you branched for this, and then I'll merge.

2024-08-07 12:37 UTC, Gabriel29306 commented
Now it's normally good.

2024-08-07 13:02 UTC, merged

2024-08-07 20:08 UTC, Gabriel29306 commented
There is a problem with my PR. But i don't know where the problem is. I'm searching th problem source.

2024-08-07 20:18 UTC, Gabriel29306 commented
I think that because the `debian/Packages` is writted with some problems, there is a alternance between stable and Canary + PTB